server:
  port: 80
  servlet:
    path: /
#连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day01
    username: root
    password: 123456
#连接池
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/day01?useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化连接数
#      initial-size: 5
#      #最小空闲连接
#      min-idle: 5
#      #最大活动连接
#      maxActive: 20
